# TODO: Figure out how to stub out the fact that
# a libraries main .cpp file does `#include "pololu-gG-led-strip-arduino-master/firmware/PololuLedStrip.h"`
#
CPP = g++
RM = rm -f
MKDIR = mkdir -p
INCLUDE_DIRS += ..
all:
	$(CPP) -I $(INCLUDE_DIRS) test1.cpp
	./a.out
